### ISSUE TITLE
更新頭像時，選擇"外部"圖片閃退！

### ISSUE THREAD

**Issue by ieyoieyo** [wildfirechat/android-chat#209]
更新頭像時，一旦點選到「外部」的圖片 即閃退！
偵錯捉到的 Exception 為：
java.io.FileNotFoundException: /storage/3036-3034/DCIM/Camera/20191118_192011.jpg (Permission denied)

測試手機：Samsung S7。選擇的圖片儲存位置是在「外接 SD卡」。

點擊圖片後的完整 Log：
2019-11-19 14:56:21.181 19416-19416/cn.wildfirechat.chat D/ViewRootImpl@7f30539[ImageGridActivity]: ViewPostImeInputStage processPointer 0
2019-11-19 14:56:21.245 19416-19416/cn.wildfirechat.chat D/ViewRootImpl@7f30539[ImageGridActivity]: ViewPostImeInputStage processPointer 1
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err: java.io.FileNotFoundException: /storage/3036-3034/DCIM/Camera/20191118_192011.jpg (Permission denied)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at java.io.FileOutputStream.open(Native Method)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at cn.wildfire.chat.kit.third.utils.ImageUtils.genThumbImgFile(ImageUtils.java:315)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at cn.wildfire.chat.kit.user.UserInfoFragment.onActivityResult(UserInfoFragment.java:188)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:7226)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at android.app.ActivityThread.-wrap22(ActivityThread.java)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at android.os.Looper.loop(Looper.java:154)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6692)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
2019-11-19 14:56:21.671 19416-19416/cn.wildfirechat.chat W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
2019-11-19 14:56:21.672 19416-19416/cn.wildfirechat.chat D/AndroidRuntime: Shutting down VM
2019-11-19 14:56:21.748 19416-19416/cn.wildfirechat.chat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.wildfirechat.chat, PID: 19416
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65636, result=-1, data=Intent {  launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 }(has extras) }} to activity {cn.wildfirechat.chat/cn.wildfire.chat.kit.user.UserInfoActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4481)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at cn.wildfire.chat.kit.user.UserInfoFragment.onActivityResult(UserInfoFragment.java:188)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
        at android.app.Activity.dispatchActivityResult(Activity.java:7226)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524) 
        at android.app.ActivityThread.-wrap22(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by ieyoieyo** [comment]
> 已经为应用授权了 SD卡的访问权限了吗？

有的。初次開啟 app 時出現的 2個權限要求，都有允許。

> 能正常发送图片消息吗？

一樣「外部」圖片不能(閃退)，內部圖片正常。

**Comment by imndx** [comment]
你好，请参考一下[这个链接](https://stackoverflow.com/questions/48172519/oreo-write-external-storage-permission)

>
```
If you get permission denied error even when the permissions are granted and you already implemented permission checks,

make sure you're not targetting api level 29:
Change targetSdkVersion and compilesdkversion from 29 to 28 or any other lower level.
```

然后，请给一下反馈，我没有有外置sd卡的设备，谢谢。

**Comment by imndx** [comment]
OK，我们再分析一下，如果你找到解决方案，可以给我们提个PR，谢谢。

**Comment by ieyoieyo** [comment]
此 issue 在上週五的 commit merge後，已經不存在了~

**Comment by ieyoieyo** [comment]
此 issue 在下面的修改後，已不復在了~
https://github.com/wildfirechat/android-chat/issues/209#issue-524813488
