### ISSUE TITLE
进入会话IM聊天页面获取历史消息的时候出现异常

### ISSUE THREAD

**Issue by jp5201314** [wildfirechat/android-chat#214]
我发送了些图片可能有点大，这个应该怎么解决
 !!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)
2019-11-21 20:02:47.607 1635-1703/com.ycjkjyxgs.gchat W/System.err: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
2019-11-21 20:02:47.607 1635-1703/com.ycjkjyxgs.gchat W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2019-11-21 20:02:47.608 1635-1703/com.ycjkjyxgs.gchat W/System.err:     at android.os.BinderProxy.transact(Binder.java:758)
2019-11-21 20:02:47.608 1635-1703/com.ycjkjyxgs.gchat W/System.err:     at cn.wildfirechat.client.IRemoteClient$Stub$Proxy.getMessages(IRemoteClient.java:1680)
2019-11-21 20:02:47.608 1635-1703/com.ycjkjyxgs.gchat W/System.err:     at cn.wildfirechat.remote.ChatManager.getMessages(ChatManager.java:1609)
2019-11-21 20:02:47.608 1635-1703/com.ycjkjyxgs.gchat W/System.err:     at com.ycjkjyxgs.gchat.kit.conversation.ConversationViewModel.lambda$loadOldMessages$0$ConversationViewModel(ConversationViewModel.java:167)
2019-11-21 20:02:47.608 1635-1703/com.ycjkjyxgs.gchat W/System.err:     at com.ycjkjyxgs.gchat.kit.conversation.-$$Lambda$ConversationViewModel$-ZTGq45_j3S0zyzTDyCUgQO3Zgc.run(Unknown Source:10)
2019-11-21 20:02:47.608 1635-1703/com.ycjkjyxgs.gchat W/System.err:     at android.os.Handler.handleCallback(Handler.java:793)
2019-11-21 20:02:47.608 1635-1703/com.ycjkjyxgs.gchat W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
2019-11-21 20:02:47.608 1635-1703/com.ycjkjyxgs.gchat W/System.err:     at android.os.Looper.loop(Looper.java:173)
2019-11-21 20:02:47.608 1635-1703/com.ycjkjyxgs.gchat W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by jp5201314** [comment]
请尽快回复一下，万分感谢

**Comment by imndx** [comment]
你可尝试将```ConversationViewModel#getMessages```里面调用```loadOldMessages```的```count```调整为10试一下

**Comment by jp5201314** [comment]
&nbsp;
 &nbsp;
  请问你们的传的消息体是不是有限制的，限制的多少，你的缩略图的工具类有个地方可能有点问题哈，你可以看看

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"notifications@github.com"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月21日(星期四) 晚上9:42
 收件人:&nbsp;"wildfirechat/android-chat"<android-chat@noreply.github.com&gt;;
 抄送:&nbsp;"＠小★猪＆"<1160873948@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
 主题:&nbsp;Re: [wildfirechat/android-chat] 进入会话IM聊天页面获取历史消息的时候出现异常 (#214)

 

 
你可尝试将ConversationViewModel#getMessages里面调用loadOldMessages的count调整为10试一下
