### ISSUE TITLE
设置>关于>功能介绍 用户协议 隐私政策 这三个点开就崩溃

### ISSUE THREAD

**Issue by NBY** [wildfirechat/android-chat#215]

**Comment by imndx** [comment]
你好，我刚试了我们demo，没有发生崩溃。请你提供一个日志方便我们分析

**Comment by NBY** [comment]
11-21 23:08:55.548 13596-13596/cn.wildfirechat.chat I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
11-21 23:08:55.561 13596-13596/cn.wildfirechat.chat I/WebViewFactory: Loading com.android.webview version 39 (5525941-x86) (code 300007)
11-21 23:08:55.567 13596-13596/cn.wildfirechat.chat I/LibraryLoader: Time to load native libraries: 2 ms (timestamps 5499-5501)
11-21 23:08:55.567 13596-13596/cn.wildfirechat.chat I/LibraryLoader: Expected native library version number "",actual native library version number ""
11-21 23:08:55.573 13596-13596/cn.wildfirechat.chat V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {11792063}
11-21 23:08:55.573 13596-13596/cn.wildfirechat.chat I/LibraryLoader: Expected native library version number "",actual native library version number ""
11-21 23:08:55.574 13596-13596/cn.wildfirechat.chat I/chromium: [INFO:library_loader_hooks.cc(104)] Chromium logging enabled: level = 0, default verbosity = 0
11-21 23:08:55.583 13596-13596/cn.wildfirechat.chat I/BrowserStartupController: Initializing chromium process, singleProcess=true
11-21 23:08:55.583 13596-13596/cn.wildfirechat.chat W/art: Attempt to remove local handle scope entry from IRT, ignoring
11-21 23:08:55.599 13596-13610/cn.wildfirechat.chat I/art: Background sticky concurrent mark sweep GC freed 127(7KB) AllocSpace objects, 0(0B) LOS objects, 2% free, 3MB/3MB, paused 5.830ms total 14.975ms
11-21 23:08:55.607 13596-13596/cn.wildfirechat.chat W/chromium: [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
11-21 23:08:55.607 13596-13664/cn.wildfirechat.chat E/BluetoothAdapter: Bluetooth binder is null
11-21 23:08:55.607 13596-13596/cn.wildfirechat.chat I/chromium: [INFO:aw_browser_main_parts.cc(65)] Load from apk succesful, fd=48 off=46184 len=3037
11-21 23:08:55.608 13596-13596/cn.wildfirechat.chat I/chromium: [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:49 off:229484 len:1089587
11-21 23:08:55.659 13596-13596/cn.wildfirechat.chat D/EGL_emulation: eglCreateContext: 0xa0824700: maj 2 min 0 rcv 2
11-21 23:08:55.659 13596-13596/cn.wildfirechat.chat D/EGL_emulation: eglMakeCurrent: 0xa0824700: ver 2 0 (tinfo 0xa1c2c400)
11-21 23:08:55.709 13596-13596/cn.wildfirechat.chat W/chromium: [WARNING:data_reduction_proxy_settings.cc(331)] SPDY proxy OFF at startup
11-21 23:08:55.712 13596-13596/cn.wildfirechat.chat W/ResourceType: No known package when getting value for resource number 0x02040003
11-21 23:08:55.712 13596-13596/cn.wildfirechat.chat D/AndroidRuntime: Shutting down VM
11-21 23:08:55.877 13596-13596/cn.wildfirechat.chat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.wildfirechat.chat, PID: 13596
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.wildfirechat.chat/cn.wildfire.chat.kit.WfcWebViewActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class cn.wildfire.chat.kit.widget.ProgressWebView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class cn.wildfire.chat.kit.widget.ProgressWebView
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at cn.wildfire.chat.kit.WfcBaseActivity.onCreate(WfcBaseActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161) 
        at cn.wildfire.chat.kit.WfcBaseActivity.onCreate(WfcBaseActivity.java:32) 
        at android.app.Activity.performCreate(Activity.java:5990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
        at android.content.res.Resources.getText(Resources.java:299)
        at android.content.res.Resources.getString(Resources.java:385)
        at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
        at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
        at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
        at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
        at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:311)
        at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
        at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:263)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
        at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
        at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:260)
        at android.webkit.WebView.<init>(WebView.java:554)
        at android.webkit.WebView.<init>(WebView.java:489)
        at android.webkit.WebView.<init>(WebView.java:472)
        at android.webkit.WebView.<init>(WebView.java:459)

**Comment by NBY** [comment]
我git clone下来后直接运行 点了用户协议就崩溃
