### ISSUE TITLE
进入app 闪退 android 7.0 三星

### ISSUE THREAD

**Issue by 704480904** [wildfirechat/android-chat#239]
2019-12-14 18:01:50.443 28620-28620/cn.wildfirechat.chat W/System.err: android.os.DeadObjectException
2019-12-14 18:01:50.447 28620-28620/cn.wildfirechat.chat W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2019-12-14 18:01:50.447 28620-28620/cn.wildfirechat.chat W/System.err:     at android.os.BinderProxy.transact(Binder.java:628)
2019-12-14 18:01:50.447 28620-28620/cn.wildfirechat.chat W/System.err:     at cn.wildfirechat.client.IRemoteClient$Stub$Proxy.getConversation(IRemoteClient.java:1401)
2019-12-14 18:01:50.447 28620-28620/cn.wildfirechat.chat W/System.err:     at cn.wildfirechat.remote.ChatManager.getConversation(ChatManager.java:1304)
2019-12-14 18:01:50.448 28620-28620/cn.wildfirechat.chat W/System.err:     at cn.wildfire.chat.kit.conversationlist.ConversationListViewModel.onReceive(ConversationListViewModel.java:156)
2019-12-14 18:01:50.448 28620-28620/cn.wildfirechat.chat W/System.err:     at cn.wildfirechat.remote.ChatManager.lambda$onReceiveMessage$1(ChatManager.java:301)
2019-12-14 18:01:50.448 28620-28620/cn.wildfirechat.chat W/System.err:     at cn.wildfirechat.remote.-$$Lambda$ChatManager$rjJzsBA79a4yCN9aP7_PTSstc8Y.run(lambda)
2019-12-14 18:01:50.448 28620-28620/cn.wildfirechat.chat W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
2019-12-14 18:01:50.448 28620-28620/cn.wildfirechat.chat W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2019-12-14 18:01:50.448 28620-28620/cn.wildfirechat.chat W/System.err:     at android.os.Looper.loop(Looper.java:154)
2019-12-14 18:01:50.448 28620-28620/cn.wildfirechat.chat W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6682)
2019-12-14 18:01:50.448 28620-28620/cn.wildfirechat.chat W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-12-14 18:01:50.448 28620-28620/cn.wildfirechat.chat W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
2019-12-14 18:01:50.448 28620-28620/cn.wildfirechat.chat W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
2019-12-14 18:01:50.636 28620-28620/cn.wildfirechat.chat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.wildfirechat.chat, PID: 28620
    java.lang.NullPointerException: Attempt to read from field 'cn.wildfirechat.model.Conversation cn.wildfirechat.model.ConversationInfo.conversation' on a null object reference
        at cn.wildfire.chat.kit.conversationlist.ConversationListViewModel.postConversationInfo(ConversationListViewModel.java:257)
        at cn.wildfire.chat.kit.conversationlist.ConversationListViewModel.onReceive(ConversationListViewModel.java:157)
        at cn.wildfirechat.remote.ChatManager.lambda$onReceiveMessage$1(ChatManager.java:301)
        at cn.wildfirechat.remote.-$$Lambda$ChatManager$rjJzsBA79a4yCN9aP7_PTSstc8Y.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by imndx** [comment]
你好，这个问题最新代码可能已修复。
请确认下出现问题的版本。

**Comment by 704480904** [comment]
![image](https://user-images.githubusercontent.com/6984303/70873286-041b6780-1fe8-11ea-998f-463bfcd1ca86.png)

**Comment by imndx** [comment]
你好，请将代码升级到最新吧，这个版本太旧了。
