### ISSUE TITLE
点击群成员查看闪退

### ISSUE THREAD

**Issue by 704480904** [wildfirechat/android-chat#248]
2019-12-27 09:20:06.731 17052-17052/cn.wildfirechat.chat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.wildfirechat.chat, PID: 17052
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.wildfirechat.chat/cn.wildfire.chat.kit.conversation.ConversationInfoActivity}: java.lang.NullPointerException: Attempt to read from field 'cn.wildfirechat.model.GroupMember$GroupMemberType cn.wildfirechat.model.GroupMember.type' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'cn.wildfirechat.model.GroupMember$GroupMemberType cn.wildfirechat.model.GroupMember.type' on a null object reference
        at cn.wildfire.chat.kit.conversation.GroupConversationInfoFragment.init(GroupConversationInfoFragment.java:157)
        at cn.wildfire.chat.kit.conversation.GroupConversationInfoFragment.onCreateView(GroupConversationInfoFragment.java:130)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
        at android.app.Activity.performStart(Activity.java:6959)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2890)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
        at android.app.ActivityThread.-wrap14(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by imndx** [comment]
这个问题已经修复了，请升级到最新代码。

**Comment by 704480904** [comment]
![image](https://user-images.githubusercontent.com/6984303/71503585-c274a180-28b0-11ea-9fb7-cc16ecf312c1.png)


应该是最新的代码了  今天早上更新编译的代码，服务器没有用私服，用的是你们的服务器  Android端我是自己clone 下来之后跑起来的
