### ISSUE TITLE
android 4.4 加载so失败

### ISSUE THREAD

**Issue by tongwenfei** [wildfirechat/android-chat#259]
android 4.4不能加载这个so库

dlopen("/data/app-lib/cn.wildfirechat.chat-2/libmarsstn.so") failed: dlopen failed: cannot locate symbol "signal" referenced by "libmarsstn.so"

**Comment by imndx** [comment]
Android 4.4 是很老的系统了，你们什么业务场景，还需要支持这么老的系统？

**Comment by minorlai** [comment]
我也出现了这个问题，退出登录，重新输入账号点击登录会 连接ConnectionStatusLogout=-2

**Comment by minorlai** [comment]
> 我也出现了这个问题，退出登录，重新输入账号点击登录会 连接ConnectionStatusLogout=-2


#00 pc 00221dc2 /data/app/cn.wildfirechat.chat-1/lib/x86/libmarsstn.so [x86]
--
2 #01 pc 001f4068 /data/app/cn.wildfirechat.chat-1/lib/x86/libmarsstn.so [x86]

三星 SM G955F  系统 5.1.1

**Comment by imndx** [comment]
> > 我也出现了这个问题，退出登录，重新输入账号点击登录会 连接ConnectionStatusLogout=-2
> 
> ## #00 pc 00221dc2 /data/app/cn.wildfirechat.chat-1/lib/x86/libmarsstn.so [x86]
> 2 #1 pc 001f4068 /data/app/cn.wildfirechat.chat-1/lib/x86/libmarsstn.so [x86]
> 
> 三星 SM G955F 系统 5.1.1

你们可能不是同一个问题，你可以重新提一个issue，并附上完整日志

**Comment by lichen1025** [comment]
你好，这个问题应该还在吧。
`09-28 08:33:02.464 17706-17724/cn.wildfirechat.chat E/dalvikvm: dlopen("/data/app-lib/cn.wildfirechat.chat-2/libmarsstn.so") failed: dlopen failed: cannot locate symbol "signal" referenced by "libmarsstn.so"...
09-28 08:33:02.477 17706-17706/cn.wildfirechat.chat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.wildfirechat.chat:marsservice, PID: 17706
    java.lang.UnsatisfiedLinkError: Native method not found: com.tencent.mars.proto.ProtoLogic.registerMessageFlag:(II)V
        at com.tencent.mars.proto.ProtoLogic.registerMessageFlag(Native Method)
        at cn.wildfirechat.client.ClientService$ClientServiceStub.registerMessageContent(ClientService.java:310)
        at cn.wildfirechat.client.ClientService.onCreate(ClientService.java:2289)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2731)
        at android.app.ActivityThread.access$1800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5292)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
        at dalvik.system.NativeStart.main(Native Method)`
Android 4.4  ，系统架构为armeabi-v7a。 应用安装后手机的对应目录是有libmarsstn这个so文件的，而且so文件的大小和aar包解压后对应目录下so文件的大小是一致的。
