### ISSUE TITLE
demo 登录成功后快速闪退到登录界面

### ISSUE THREAD

**Issue by lliuhaomin** [wildfirechat/android-chat#278]
demo 登录成功后快速闪退到登录界面

android 日志

02/28 18:09:07: Launching 'chat' on Unknown Device.
$ adb shell am start -n "cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: cn.wildfirechat.chat | cn.wildfirechat.chat.test
Waiting for application to come online: cn.wildfirechat.chat | cn.wildfirechat.chat.test
Connecting to cn.wildfirechat.chat
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application cn.wildfirechat.chat is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8600', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10245(cn.wildfirechat.chat) identical 1 line
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1355)
I/Perf: Connecting to perf service.
I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
    VM has multidex support, MultiDex support library is disabled.
W/ldfirechat.chat: type=1400 audit(0.0:130263): avc: denied { read } for name="anr" dev="sda29" ino=6029313 scontext=u:r:untrusted_app:s0:c245,c256,c512,c768 tcontext=u:object_r:anr_data_file:s0 tclass=dir permissive=0
E/avenginekit: engine init
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/ldfirechat.cha: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
    Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
    Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
W/System.err: java.io.FileNotFoundException: /system/build.prop (Permission denied)
W/System.err:     at java.io.FileInputStream.open0(Native Method)
W/System.err:     at java.io.FileInputStream.open(FileInputStream.java:231)
W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:165)
W/System.err:     at cn.wildfirechat.push.PushService.getSystem(PushService.java:381)
W/System.err:     at cn.wildfirechat.push.PushService.init(PushService.java:63)
W/System.err:     at cn.wildfire.chat.app.MyApp.onCreate(MyApp.java:33)
W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5954)
W/System.err:     at android.app.ActivityThread.access$1200(ActivityThread.java:200)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loop(Looper.java:201)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6815)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/mcssdk---: MCS-->isExistPackage NameNotFoundException:com.coloros.mcs
V/xiaomi: [Thread:2] Perf_code  packetType  2037  length 259
E/MessageViewHolderManager: re-register message view holder SimpleNotificationMessageContentViewHolder
V/xiaomi: [Thread:8049] ASSEMBLE_PUSH : assemble push register
V/xiaomi: [Thread:8045] Perf_code  packetType  2010  length 200
V/xiaomi: java.lang.IllegalArgumentException
        at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:595)
        at com.xiaomi.channel.commonutils.misc.h.a(Unknown Source:58)
        at com.xiaomi.clientreport.manager.a.f(Unknown Source:33)
        at com.xiaomi.clientreport.manager.a.b(Unknown Source:15)
        at com.xiaomi.clientreport.manager.ClientReportClient.init(Unknown Source:74)
        at com.xiaomi.mipush.sdk.MiPushClient.initEventPerfLogic(Unknown Source:22)
        at com.xiaomi.mipush.sdk.MiPushClient.initialize(Unknown Source:771)
        at com.xiaomi.mipush.sdk.ag.run(Unknown Source:15)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
I/ldfirechat.cha: The ClassLoaderContext is a special shared library.
W/ldfirechat.cha: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/ldfirechat.cha: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
W/Binder:intercep: type=1400 audit(0.0:130267): avc: denied { getattr } for path="/data/data/com.miui.contentcatcher" dev="sda29" ino=1835051 scontext=u:r:untrusted_app:s0:c245,c256,c512,c768 tcontext=u:object_r:system_app_data_file:s0 tclass=dir permissive=0
W/ldfirechat.cha: Accessing hidden method Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application; (light greylist, linking)
D/ViewContentFactory: initViewContentFetcherClass
    getInterceptorPackageInfo
D/ViewContentFactory: getInitialApplication took 3ms
D/ViewContentFactory: packageInfo.packageName: com.miui.catcherpatch
W/Binder:intercep: type=1400 audit(0.0:130268): avc: denied { getattr } for path="/data/data/com.miui.catcherpatch" dev="sda29" ino=1835341 scontext=u:r:untrusted_app:s0:c245,c256,c512,c768 tcontext=u:object_r:system_app_data_file:s0 tclass=dir permissive=0
D/ViewContentFactory: initViewContentFetcherClass took 65ms
I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory: createInterceptor took 67ms
W/Looper: Slow Looper: Activity cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity is 3363ms late (wall=425ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 1 msg, msg 1 took 3435ms (late=1ms h=android.app.ActivityThread$H w=110)
I/Adreno: QUALCOMM build                   : 7ff4f54, I4460aa6217
    Build Date                       : 12/14/18
    OpenGL ES Shader Compiler Version: EV031.25.03.02
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
I/Adreno: Build Config                     : S P 6.0.7 AArch32
I/Adreno: PFP: 0x016ee176, ME: 0x00000000
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
    android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
V/xiaomi: [Thread:8049] receive an intent from server, action=com.xiaomi.mipush.RECEIVE_MESSAGE
V/xiaomi: receiving an empty message, drop
I/Timeline: Timeline: Activity_launch_request time:148999289 intent:Intent { cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity }
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@a715040
D/ViewContentFactory: initViewContentFetcherClass
I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory: createInterceptor took 1ms
I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
W/ldfirechat.cha: Accessing hidden method Landroid/app/ActivityManagerNative;->getDefault()Landroid/app/IActivityManager; (light greylist, reflection)
W/BuglyThread-3: type=1400 audit(0.0:130273): avc: denied { search } for name="usb" dev="sysfs" ino=52843 scontext=u:r:untrusted_app:s0:c245,c256,c512,c768 tcontext=u:object_r:sysfs_usb_supply:s0 tclass=dir permissive=0
W/Activity: Slow Operation: Activity cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity onCreate took 805ms
I/ldfirechat.cha: ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
W/InputEventReceiver: Slow Input: took 172ms in dispatching, now at finishInputEvent (MotionEvent: event_seq=1, seq=1313346, action=ACTION_UP)
I/AssistStructure: Flattened final assist data: 3224 bytes, containing 1 windows, 11 views
W/InputEventReceiver: Slow Input: took 130ms in dispatching, now at finishInputEvent (MotionEvent: event_seq=3, seq=1313424, action=ACTION_UP)
I/AssistStructure: Flattened final assist data: 3264 bytes, containing 1 windows, 11 views
W/Looper: Slow Looper: doFrame is 448ms late because of 1 msg, msg 1 took 444ms (late=3ms h=android.view.ViewRootImpl$ViewRootHandler c=android.view.View$PerformClick)
W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
I/Timeline: Timeline: Activity_launch_request time:149023083 intent:Intent { flg=0x8000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.MainActivity }
I/Choreographer: Skipped 83 frames!  The application may be doing too much work on its main thread.
W/Looper: Slow Looper: doFrame is 1391ms late because of 1 msg, msg 1 took 1397ms (late=4ms h=android.os.Handler c=cn.wildfire.chat.kit.net.SimpleCallback$1)
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@58fcc2
D/ViewContentFactory: initViewContentFetcherClass
I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory: createInterceptor took 1ms
I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
W/ldfirechat.cha: Accessing hidden field Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate; (light greylist, reflection)
W/Activity: Slow Operation: Activity cn.wildfirechat.chat/cn.wildfire.chat.app.main.MainActivity onCreate took 616ms
I/Choreographer: Skipped 94 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Davey! duration=1708ms; Flags=0, IntendedVsync=149024008872780, Vsync=149025575539384, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=149025581599031, AnimationStart=149025581748093, PerformTraversalsStart=149025582482051, DrawStart=149025583757572, SyncQueued=149025709240072, SyncStart=149025709335489, IssueDrawCommandsStart=149025709475385, SwapBuffers=149025716599031, FrameCompleted=149025717114604, DequeueBufferDuration=1938000, QueueBufferDuration=253000, 
I/Timeline: Timeline: Activity_launch_request time:149025744 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149025772 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149025829 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149025869 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149025903 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149025941 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026138 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026174 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026238 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026301 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026332 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026364 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026405 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026435 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
W/Glide: Load failed for null with size [0x0]
    class com.bumptech.glide.load.engine.GlideException: Received null model
I/Timeline: Timeline: Activity_launch_request time:149026556 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026584 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026659 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Timeline: Timeline: Activity_launch_request time:149026694 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
I/Choreographer: Skipped 68 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Davey! duration=1613ms; Flags=1, IntendedVsync=149025590363926, Vsync=149026723697214, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=149026730800957, AnimationStart=149026731113978, PerformTraversalsStart=149026732943353, DrawStart=149027154213509, SyncQueued=149027197309811, SyncStart=149027197417155, IssueDrawCommandsStart=149027197797103, SwapBuffers=149027202923093, FrameCompleted=149027203749863, DequeueBufferDuration=445000, QueueBufferDuration=250000, 
W/Looper: Slow Looper: doFrame is 1140ms late because of 117 msg, msg 1 took 136ms (late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver), msg 5 took 52ms (late=2385ms h=android.os.Handler c=cn.wildfirechat.remote.ChatManager$3), msg 42 took 147ms (late=1985ms h=android.view.ViewRootImpl$ViewRootHandler c=androidx.appcompat.app.ToolbarActionBar$1), msg 47 took 54ms (late=1970ms h=android.os.Handler c=cn.wildfirechat.remote.ChatManager$3), msg 102 took 75ms (late=1372ms h=android.os.Handler c=androidx.lifecycle.LiveData$1)
I/Timeline: Timeline: Activity_launch_request time:149027252 intent:Intent { flg=0x10008000 cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity }
W/Glide: Load failed for null with size [0x0]
    class com.bumptech.glide.load.engine.GlideException: Received null model
W/Looper: Slow Looper: Activity cn.wildfirechat.chat/cn.wildfire.chat.app.main.MainActivity is 1529ms late (wall=47ms running=0ms ClientTransaction{ lifecycleRequest=android.app.servertransaction.PauseActivityItem }) because of 121 msg, msg 4 took 52ms (late=2385ms h=android.os.Handler c=cn.wildfirechat.remote.ChatManager$3), msg 41 took 147ms (late=1985ms h=android.view.ViewRootImpl$ViewRootHandler c=androidx.appcompat.app.ToolbarActionBar$1), msg 46 took 54ms (late=1970ms h=android.os.Handler c=cn.wildfirechat.remote.ChatManager$3), msg 101 took 75ms (late=1372ms h=android.os.Handler c=androidx.lifecycle.LiveData$1), msg 117 took 501ms (late=1140ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@3da7cff
D/ViewContentFactory: initViewContentFetcherClass
I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory: createInterceptor took 0ms
W/Looper: Slow Looper: Activity cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity is 1058ms late (wall=218ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 76 msg, msg 46 took 75ms (late=1372ms h=android.os.Handler c=androidx.lifecycle.LiveData$1), msg 62 took 501ms (late=1140ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
W/Looper: Slow Looper: Activity cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity is 1271ms late (wall=15ms running=0ms ClientTransaction{ lifecycleRequest=android.app.servertransaction.PauseActivityItem }) because of 69 msg, msg 38 took 75ms (late=1372ms h=android.os.Handler c=androidx.lifecycle.LiveData$1), msg 54 took 501ms (late=1140ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver), msg 69 took 218ms (late=1058ms h=android.app.ActivityThread$H w=159)
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@c17f583
D/ViewContentFactory: initViewContentFetcherClass
I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory: createInterceptor took 1ms
W/Looper: Slow Looper: Activity cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity is 777ms late (wall=220ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 23 msg, msg 1 took 501ms (late=1140ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver), msg 16 took 218ms (late=1058ms h=android.app.ActivityThread$H w=159)
I/Choreographer: Skipped 39 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Davey! duration=707ms; Flags=0, IntendedVsync=149027172828720, Vsync=149027822828694, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=149027838655176, AnimationStart=149027838994811, PerformTraversalsStart=149027839018249, DrawStart=149027860365019, SyncQueued=149027876668040, SyncStart=149027876754603, IssueDrawCommandsStart=149027876998092, SwapBuffers=149027878512519, FrameCompleted=149027879960071, DequeueBufferDuration=236000, QueueBufferDuration=515000, 
W/Looper: Slow Looper: doFrame is 666ms late because of 29 msg, msg 1 took 501ms (late=1140ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver), msg 16 took 218ms (late=1058ms h=android.app.ActivityThread$H w=159), msg 24 took 220ms (late=777ms h=android.app.ActivityThread$H w=159)
W/Looper: Slow Looper: Activity cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity is 753ms late (wall=17ms running=0ms ClientTransaction{ lifecycleRequest=android.app.servertransaction.PauseActivityItem }) because of 29 msg, msg 12 took 218ms (late=1058ms h=android.app.ActivityThread$H w=159), msg 20 took 220ms (late=777ms h=android.app.ActivityThread$H w=159), msg 26 took 145ms (late=666ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
D/ViewContentFactory: initViewContentFetcherClass
I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory: createInterceptor took 2ms
W/Looper: Slow Looper: Activity cn.wildfirechat.chat/cn.wildfire.chat.app.main.SplashActivity is 331ms late (wall=179ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem }) because of 14 msg, msg 1 took 220ms (late=777ms h=android.app.ActivityThread$H w=159), msg 7 took 145ms (late=666ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver), msg 14 took 75ms (late=1ms h=android.view.Choreographer$FrameHandler w=0)
I/Timeline: Timeline: Activity_launch_request time:149028498 intent:Intent { cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity }
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f81dec1
D/ViewContentFactory: initViewContentFetcherClass
I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory: createInterceptor took 0ms
I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
I/Timeline: Timeline: Activity_launch_request time:149029404 intent:Intent { cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity }
I/Timeline: Timeline: Activity_launch_request time:149029452 intent:Intent { cmp=cn.wildfirechat.chat/cn.wildfire.chat.app.login.SMSLoginActivity }
W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@33420ac
D/ViewContentFactory: initViewContentFetcherClass
I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory: createInterceptor took 1ms
I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.

**Comment by heavyrain2012** [comment]
需要抓协议栈日志，协议栈日志的方法请参考文档中的常见问题

**Comment by imndx** [comment]
no response.
