### ISSUE TITLE
试用的过程中，出现的一个必崩的问题

### ISSUE THREAD

**Issue by newlai913** [wildfirechat/android-chat#3]
具体崩溃信息如下：
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=45570, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/3146 flg=0x1 }} to activity {cn.wildfirechat.chat/cn.wildfire.chat.kit.conversation.ConversationActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3146
 at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
 at android.app.ActivityThread.handleSendResult(ActivityThread.java:4434)
 at android.app.ActivityThread.-wrap19(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:6704)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/3146
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
 at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
 at android.content.ContentResolver.query(ContentResolver.java:756)
 at android.content.ContentResolver.query(ContentResolver.java:705)
 at android.content.ContentResolver.query(ContentResolver.java:663)
 at cn.wildfire.chat.kit.utils.FilePathUtil.getDataColumn(FilePathUtil.java:148)
 at cn.wildfire.chat.kit.utils.FilePathUtil.getPath(FilePathUtil.java:96)
 at cn.wildfire.chat.kit.utils.FilePathUtil.getRealPath(FilePathUtil.java:24)
 at cn.wildfire.chat.kit.conversation.ext.FileExt.onActivityResult(FileExt.java:42)
 at cn.wildfire.chat.kit.conversation.ext.core.ConversationExtension.onActivityResult(ConversationExtension.java:140)
 at cn.wildfire.chat.kit.conversation.ConversationActivity.onActivityResult(ConversationActivity.java:454)
 at android.app.Activity.dispatchActivityResult(Activity.java:7310)
 at android.app.ActivityThread.deliverResults(ActivityThread.java:4387)
 ... 9 more

操作步骤如下：
进入聊天室->点击底栏的+号->选择文件选项->选择左边栏的下载内容项->任意选择一个文件->崩溃

**Comment by imndx** [comment]
你提的这个issue真专业呀。
谢谢反馈，我们尽快修复。

**Comment by newlai913** [comment]
问题好像没解决诶，今天试了一下，还是崩溃，只是异常信息不一样了
`java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=45570, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/2508 flg=0x1 }} to activity {cn.wildfirechat.chat/cn.wildfire.chat.kit.conversation.ConversationActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/2508
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4434)
	at android.app.ActivityThread.-wrap19(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6704)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/2508
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
	at android.content.ContentResolver.query(ContentResolver.java:756)
	at android.content.ContentResolver.query(ContentResolver.java:705)
	at android.content.ContentResolver.query(ContentResolver.java:663)
	at cn.wildfire.chat.kit.utils.FilePathUtil.getDataColumn(FilePathUtil.java:148)
	at cn.wildfire.chat.kit.utils.FilePathUtil.getPath(FilePathUtil.java:96)
	at cn.wildfire.chat.kit.utils.FilePathUtil.getRealPath(FilePathUtil.java:24)
	at cn.wildfire.chat.kit.conversation.ext.FileExt.onActivityResult(FileExt.java:42)
	at cn.wildfire.chat.kit.conversation.ext.core.ConversationExtension.onActivityResult(ConversationExtension.java:140)
	at cn.wildfire.chat.kit.conversation.ConversationActivity.onActivityResult(ConversationActivity.java:454)
	at android.app.Activity.dispatchActivityResult(Activity.java:7310)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4387)
	... 9 more`

**Comment by imndx** [comment]
哦哦，sorry，我提交代码之后，忘记重新release一个版本了。
你可以加我QQ：2377468043，我给你传一个版本吧。

github上，计划晚上发布新的版本。
