### ISSUE TITLE
希望能把kit做成library 方便像uniapp,apicloud这种混合式开发调用界面

### ISSUE THREAD

**Issue by xhun2015** [wildfirechat/android-chat#390]
我相信很多对于原生开发不熟悉，使用混合式开发APP的不在少数。
但是想要集成你们的产品，就基本只有放弃。
因为像uniapp，apicloud这种两种比较常用的混合式开发，必须把原生做成一个library使用。
而野火目前直接做成library是不行的，因为butterKnife在library中R.xx.yyy并不是一个常量。
需要改成R2,但是我尝试使用R2还是遇到了很多问题。我不是一个原生开发者，只是懂一点点，所以花了一天时间解决了大部分错误后，能运行起来了。但是启动就闪退。分析问题出现在通讯录用户列表这块。layoutRes.resId()使用这个会报android.content.res.Resources$NotFoundException错误，改成R.layout.contact_item_contact可以正常执行：

HeaderValueWrapper wrapper = headerValues.get(viewType);
            LayoutRes layoutRes = wrapper.headerViewHolderClazz.getAnnotation(LayoutRes.class);
            Log.i("xtf",layoutRes.resId()+"---"+R.layout.contact_item_contact);
            //itemView = LayoutInflater.from(fragment.getActivity()).inflate(layoutRes.resId(), parent, false);
            itemView = LayoutInflater.from(fragment.getContext()).inflate(R.layout.contact_item_contact, parent, false);
            try {
                Constructor constructor = wrapper.headerViewHolderClazz.getConstructor(Fragment.class, UserListAdapter.class, View.class);
                viewHolder = (HeaderViewHolder) constructor.newInstance(fragment, this, itemView);
            } catch (Exception e) {
                e.printStackTrace();
                throw new RuntimeException("create header viewHolder failed");
            }
但是viewHolder = (HeaderViewHolder) constructor.newInstance(fragment, this, itemView);又报错闪退
W/System.err: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at cn.wildfire.chat.kit.contact.UserListAdapter.onCreateViewHolder(UserListAdapter.java:82)
W/System.err:     at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7046)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6214)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6097)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6093)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
W/System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4115)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3521)
        at android.view.View.measure(View.java:22105)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
W/System.err:     at android.view.View.measure(View.java:22105)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
        at android.view.View.measure(View.java:22105)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:958)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22105)
W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
W/System.err:     at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22105)
W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22105)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:727)
W/System.err:     at android.view.View.measure(View.java:22105)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2467)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1549)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1806)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6886)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:841)
        at android.view.Choreographer.doFrame(Choreographer.java:772)
W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
W/System.err: Caused by: java.lang.IllegalStateException: Required view 'unreadFriendRequestCountTextView' with ID 2131296948 for field 'unreadRequestCountTextView' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
W/System.err:     at butterknife.internal.Utils.findRequiredView(Utils.java:84)
        at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:96)
        at cn.wildfire.chat.kit.contact.viewholder.header.FriendRequestViewHolder_ViewBinding.<init>(FriendRequestViewHolder_ViewBinding.java:21)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at butterknife.ButterKnife.bind(ButterKnife.java:170)
        at cn.wildfire.chat.kit.contact.viewholder.header.FriendRequestViewHolder.<init>(FriendRequestViewHolder.java:27)
    	... 70 more

真的是原生能力有限。我花了一天时间改到目前这个程度，不知道后面还有多少错误。到了真的无能为力的时候就只有放弃了，毕竟时间有限。真心希望得到官方支持。我相信也是很多想使用野火IM的非原生开发人员所希望的。

**Comment by xhun2015** [comment]
我相信你们官方只需要花几个小时就能做成library。为什么就不能完善下呢。非原生开发者我相信比原生开发者数量更庞大。如果做成library你们都要花几天甚至上10天，麻烦告诉我一声，感谢感谢，我好选择其他方案，真的项目紧赶时间

**Comment by imndx** [comment]
你好，请用最新代码测试，遇到什么问题，请在这个issue下进行反馈，谢谢。

```client``` 是im功能相关library module
```uikit``` 是ui相关library module。

**Comment by xhun2015** [comment]
经测试weex,uiapp,apicloud 无法使用野火IM做成对应平台的插件,因为这几个平台都暂时都不支持androidx。不过uniapp可以使用他的小程序SDK，这个就相当于将野火作为宿主app,uniapp编写出来的app作为小程序集成到宿主APP,宿主APP像uniapp小程序暴露会话列表UI组件，小程序中嵌入会话列表。目前我已使用这种方案完成了集成。集成过程中也遇到了问题，由于uniapp的UI组件实质上是用weex的。但是weex不支持androidx下的fragment,只能复制一份ConversationList然后改成android.app.fragement,并去掉viewmodel,在fragment中实现监听接口，改动不是很大。

所以目前野火无法满足混合式开发者，如果想满足只有另外弄一个使用v4,v7的支持库的，或者等这些平台支持androidx

**Comment by imndx** [comment]
谢谢你的反馈。
野火IM UI部分，大量使用了androidx的特性，改成v4、v7工作量比较大，目前可能没精力去做这个改动。

**Comment by xhun2015** [comment]
理解。不过你们的产品已基本成型，基本上能满足绝大部分需要集成IM的项目。所以其实你们现在最重要的是让更多开发者使用，只有更多开发者使用你们的产品，你们才能更快成才。其实对于原生开发者他们在选择使用IM的选择更多，而非原生开发者的选择更少，所以你们如果多花点经历照顾非原生开发者，我相信会更加成功。仅个人建议，我相信你们不单单做IM,所以精力有限也很正常

**Comment by imndx** [comment]
补充一下，[jetifier工具](https://developer.android.google.cn/studio/command-line/jetifier)应当能AndroidX 和 support互转。

**Comment by yoyomule** [comment]
混合开发者现在可以用了吗?

**Comment by imndx** [comment]
已支持。

另外，还以可以参考：[uni-chat](https://github.com/wildfirechat/uni-chat) 和 [uni-wfc-client](https://gitee.com/wfchat/uni-wfc-client)
