### ISSUE TITLE
获取消息闪退

### ISSUE THREAD

**Issue by woyaozuoai** [wildfirechat/android-chat#408]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at cn.wildfire.chat.kit.conversation.message.viewholder.f.f(MessageViewHolderManager.java:1)
	at cn.wildfire.chat.kit.conversation.n0.w(ConversationMessageAdapter.java:5)
	at androidx.recyclerview.widget.RecyclerView$g.d(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$w.J(RecyclerView.java:34)
	at androidx.recyclerview.widget.RecyclerView$w.q(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$w.p(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$c.e(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.LinearLayoutManager.W2(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.s2(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.q1(LinearLayoutManager.java:71)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:9)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at androidx.appcompat.widget.h0.F(LinearLayoutCompat.java:1)
	at androidx.appcompat.widget.h0.A(LinearLayoutCompat.java:24)
	at androidx.appcompat.widget.h0.onLayout(LinearLayoutCompat.java:2)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2883)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2410)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1545)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7425)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1034)
	at android.view.Choreographer.doCallbacks(Choreographer.java:830)
	at android.view.Choreographer.doFrame(Choreographer.java:765)
	at android.view.Choreographer$。。。。。。。。。。。。。。。。。。

**Comment by imndx** [comment]
你好，请问这是怎么复现的？
是官方demo吗？

**Comment by woyaozuoai** [comment]
> 你好，请问这是怎么复现的？
> 是官方demo吗？

卸载后重新新安装app,点击对话框拉取信息获取信息闪退,重新打开对话框正常，
