### ISSUE TITLE
集成到项目中报错

### ISSUE THREAD

**Issue by yanjwgit** [wildfirechat/android-chat#438]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***
#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

集成到我的项目中报错
> Task :app:processDebugResources FAILED
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"C:\\Users\\Administrator\\Desktop\\WNSJOA\\wnsjoa\\app\\src\\main\\AndroidManifest.xml","position":{"startLine":270,"startColumn":12,"endColumn":60}}],"original":"C:\\Users\\Administrator\\Desktop\\WNSJOA\\wnsjoa\\app\\src\\main\\AndroidManifest.xml:271:13-61: AAPT: error: not well-formed (invalid token).\n    ","tool":"AAPT"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Administrator\Desktop\WNSJOA\wnsjoa\app\src\main\AndroidManifest.xml:271:13-61: AAPT: error: not well-formed (invalid token).
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
	at org.gradle.workers.internal.DefaultWorkerExecutor$WorkerExecution.waitForCompletion(DefaultWorkerExecutor.java:285)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:115)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForCompletion(DefaultAsyncWorkTracker.java:87)
	at org.gradle.workers.internal.DefaultWorkerExecutor.await(DefaultWorkerExecutor.java:150)
	at com.android.build.gradle.internal.tasks.Workers$WorkerExecutorAdapter.await(Workers.kt:282)
	... 185 more
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
C:\Users\Administrator\Desktop\WNSJOA\wnsjoa\app\src\main\AndroidManifest.xml:273:13-49: AAPT: error: not well-formed (invalid token).
    
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create(Aapt2Exception.kt:45)
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create$default(Aapt2Exception.kt:39)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:195)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteLinkException(Aapt2ErrorUtils.kt:126)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$AaptSplitInvoker.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.kt:848)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$AaptSplitInvoker.run(LinkApplicationAndroidResourcesTask.kt:722)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:55)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:105)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:99)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	... 3 more

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

添加implementation project(':uikit')后报上面的错误，注释implementation project(':uikit')后项目又恢复正常。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
提示```C:\Users\Administrator\Desktop\WNSJOA\wnsjoa\app\src\main\AndroidManifest.xml:271```不对，请确认下

**Comment by yanjwgit** [comment]
确认了很多遍了，报错的这一行是绝对正确的，而且我把uikit依赖注销后我的项目就恢复正常了，添加uikit依赖后就报那个错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "imndx"<notifications@github.com&gt;; 
发送时间: 2020年9月11日(星期五) 下午4:38
收件人: "wildfirechat/android-chat"<android-chat@noreply.github.com&gt;; 
抄送: "暖若安阳、"<874807039@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wildfirechat/android-chat] 集成到项目中报错 (#438)





 
提示C:\Users\Administrator\Desktop\WNSJOA\wnsjoa\app\src\main\AndroidManifest.xml:271不对，请确认下
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by imndx** [comment]
@yanjwgit  反馈是```Manifest```文件中的中文导致的问题，将所有的中文移动到```strings.xml```解决了问题。
