### ISSUE TITLE
最新版本0.8.4，私聊发送名片闪退

### ISSUE THREAD

**Issue by kulong51** [wildfirechat/android-chat#495]
-19 10:00:58.107 32373-32373/cn.wildfirechat.chat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.wildfirechat.chat, PID: 32373
    java.lang.NoClassDefFoundError: cn.wildfire.chat.kit.contact.-$$Lambda$ContactListFragment$JWlKBK0pEkYQJrSjIs9yCYNYa8A
        at cn.wildfire.chat.kit.contact.ContactListFragment.lambda$afterViews$1$ContactListFragment(ContactListFragment.java:72)
        at cn.wildfire.chat.kit.contact.-$$Lambda$ContactListFragment$7j9U204hGsc3jvvJ9M68IEKnU3A.onChanged(lambda)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:5958)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by imndx** [comment]
请问是必现的吗？我没复现呢

**Comment by imndx** [comment]
no response.
