### ISSUE TITLE
java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.example.bzjlsgl_platform_01-2/base.apk:classes4.dex)

### ISSUE THREAD

**Issue by meihaiwei** [wildfirechat/android-chat#507]
集成api 'org.webrtc:google-webrtc:1.0.30039'这个，报上边这个错误
java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.example.bzjlsgl_platform_01-2/base.apk:classes4.dex)
 at cn.wildfirechat.avenginekit.PeerConnectionClient.<init>()
 at cn.wildfirechat.avenginekit.AVEngineKit.b()
 at cn.wildfirechat.avenginekit.AVEngineKit.g()
 at cn.wildfirechat.avenginekit.AVEngineKit$CallSession.startPreview()
 at cn.wildfire.chat.kit.voip.SingleVideoFragment.init(SingleVideoFragment.java:360)
 at cn.wildfire.chat.kit.voip.SingleVideoFragment.onCreateView(SingleVideoFragment.java:87)

**Comment by imndx** [comment]
你好，提issue之前，可以先搜索一下是否有类型的issue哈。

请参考：#378
