### ISSUE TITLE
拨打视频崩溃

### ISSUE THREAD

**Issue by shunFSKi** [wildfirechat/android-chat#525]
报错日志：
```
E/AndroidRuntime(14624): FATAL EXCEPTION: main
E/AndroidRuntime(14624): Process: com.qizhi.flutter_nas, PID: 14624
E/AndroidRuntime(14624): java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.qizhi.flutter_nas-6KYWxES3KhDfrG50xYXFfQ==/base.apk:classes3.dex)
E/AndroidRuntime(14624): 	at cn.wildfirechat.avenginekit.PeerConnectionClient.<init>(Unknown Source:20)
E/AndroidRuntime(14624): 	at cn.wildfirechat.avenginekit.AVEngineKit.b(Unknown Source:6)
E/AndroidRuntime(14624): 	at cn.wildfirechat.avenginekit.AVEngineKit.g(Unknown Source:0)
E/AndroidRuntime(14624): 	at cn.wildfirechat.avenginekit.AVEngineKit$CallSession.startPreview(Unknown Source:32)
E/AndroidRuntime(14624): 	at cn.wildfire.chat.kit.voip.SingleVideoFragment.init(SingleVideoFragment.java:367)
E/AndroidRuntime(14624): 	at cn.wildfire.chat.kit.voip.SingleVideoFragment.onCreateView(SingleVideoFragment.java:89)
E/AndroidRuntime(14624): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
E/AndroidRuntime(14624): 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2621)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2569)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
E/AndroidRuntime(14624): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
E/AndroidRuntime(14624): 	at cn.wildfire.chat.kit.voip.SingleCallActivity.onStart(SingleCallActivity.java:82)
E/AndroidRuntime(14624): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1339)
E/AndroidRuntime(14624): 	at android.app.Activity.performStart(Activity.java:7403)
E/AndroidRuntime(14624): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
E/AndroidRuntime(14624): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
E/AndroidRuntime(14624): 	at android.app.ActivityThread.-wrap12(Unknown Source:0)
E/AndroidRuntime(14624): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
E/AndroidRuntime(14624): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime(14624): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(14624): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/AndroidRuntime(14624): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14624): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime(14624): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
I/Process (14624): Sending signal. PID: 14624 SIG: 9
Lost connection to device.
```
调用方法：
```
void videoCall(String targetId) {
        Conversation conversation = new Conversation(Conversation.ConversationType.Single, targetId);
        AVEngineKit.Instance().startCall(conversation, Collections.singletonList(targetId), false, null);

        AudioManager audioManager = (AudioManager) getContext().getSystemService(Context.AUDIO_SERVICE);
        audioManager.setMode(AudioManager.MODE_NORMAL);
        audioManager.setSpeakerphoneOn(true);

        Intent voip = new Intent(getContext(), SingleCallActivity.class);
        startActivity(getContext(), voip);

        VoipCallService.start(getContext(), false);
    }

    public static void startActivity(Context context, Intent intent) {
        if (context instanceof Activity) {
            context.startActivity(intent);
            ((Activity) context).overridePendingTransition(android.R.anim.fade_in, android.R.anim.fade_out);
        } else {
            Intent main = new Intent(context.getPackageName() + ".main");
//            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            PendingIntent pendingIntent = PendingIntent.getActivities(context, 100, new Intent[]{main, intent}, PendingIntent.FLAG_UPDATE_CURRENT);
            try {
                pendingIntent.send();
            } catch (PendingIntent.CanceledException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }
```
问题：
```
跳转到视频页面直接就退出应用了，这个报错日志能定位到错误吗？
```

**Comment by imndx** [comment]
#378
