### ISSUE TITLE
对接其他第三方sdk 导致 libc++_shared.so 冲突，导致找不到 registerMessageFlag 方法

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#545]
对接其他第三方sdk 导致 libc++_shared.so 冲突，设置过滤冲突packagingOptions 之后导致IM

java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mars.proto.ProtoLogic.registerMessageFlag(int, int) (tried Java_com_tencent_mars_proto_ProtoLogic_registerMessageFlag and Java_com_tencent_mars_proto_ProtoLogic_registerMessageFlag__II)
        at com.tencent.mars.proto.ProtoLogic.registerMessageFlag(Native Method)
        at cn.wildfirechat.client.ClientService$ClientServiceStub.registerMessageContent(ClientService.java:331)
        at cn.wildfirechat.client.ClientService.onCreate(ClientService.java:2354)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3604)
        at android.app.ActivityThread.access$1400(ActivityThread.java:202)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

 java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mars.proto.ProtoLogic.registerMessageFlag(int, int) (tried Java_com_tencent_mars_proto_ProtoLogic_registerMessageFlag and Java_com_tencent_mars_proto_ProtoLogic_registerMessageFlag__II)
        at com.tencent.mars.proto.ProtoLogic.registerMessageFlag(Native Method)
        at cn.wildfirechat.client.ClientService$ClientServiceStub.registerMessageContent(ClientService.java:331)
        at cn.wildfirechat.client.ClientService.onCreate(ClientService.java:2354)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3604)
        at android.app.ActivityThread.access$1400(ActivityThread.java:202)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by imndx** [comment]
请在应用的```build.gradle``` 里面，添加如下配置测试一下：
```android {

....
packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
    }
....

```

**Comment by imndx** [comment]
no response.

**Comment by imndx** [comment]
> 请在应用的`build.gradle` 里面，添加如下配置测试一下：
> 
> ```
> 
> ....
> packagingOptions {
>         pickFirst 'lib/x86/libc++_shared.so'
>         pickFirst 'lib/arm64-v8a/libc++_shared.so'
>         pickFirst 'lib/armeabi-v7a/libc++_shared.so'
>         pickFirst 'lib/x86_64/libc++_shared.so'
>     }
> ....
> ```

这样配置后，可以编译通过，但如果其他第三方SDK中的```libc++_shared.so```版本和野火IM所使用的```libc++_shared.so```版本不一致时，某些系统版本上可能会出现崩溃，这种情况目前没有好的解决方案，可以做以下尝试：

1. 找出哪些第三方```aar```里面包含了```libc++_shared.so```。
2. 将所有```aar```中的```libc++_shared.so```统一到一个版本，但具体统一到哪个版本，需要对比测试一下。
   > ```aar```其实就是一个```zip```压缩文件，可以解压，替换文件，重新压缩，并修改后缀名。
3. 保持上面的```packagingOptions```配置。


PS：野火IM所使用的```libc++_shared.so```来自于ndk ```18.1.5063045```版本
