### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=3; index=3

### ISSUE THREAD

**Issue by scsfwgy** [wildfirechat/android-chat#555]
特定场景下必现错误。
这个用户正常用-后台封禁这个用户-用户再次登录，链接不上-后台解封这个用户-用户再次登陆，就报这个错误。

![image](https://user-images.githubusercontent.com/16045179/121317936-58817800-c93d-11eb-9c04-69dac5a6404b.png)

```
2021-06-09 16:08:40.825 22890-23348/com.superchain.lbanknew E/CrashReport: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
        at cn.wildfire.chat.kit.third.utils.ImageUtils$2$1.lambda$onSuccess$0$ImageUtils$2$1(ImageUtils.java:339)
        at cn.wildfire.chat.kit.third.utils.-$$Lambda$ImageUtils$2$1$8qc-DggK4Nv-DbCKFtDGCr7EHsE.run(Unknown Source:12)
        at java.lang.Thread.run(Thread.java:929)
2021-06-09 16:08:40.825 22890-23348/com.superchain.lbanknew E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
2021-06-09 16:08:40.839 1087-1341/? E/Parcel: Reading a NULL string not supported here.
2021-06-09 16:08:40.846 22890-23350/com.superchain.lbanknew E/AndroidRuntime: FATAL EXCEPTION: Thread-35
    Process: com.superchain.lbanknew, PID: 22890
    java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
        at cn.wildfire.chat.kit.third.utils.ImageUtils$2$1.lambda$onSuccess$0$ImageUtils$2$1(ImageUtils.java:339)
        at cn.wildfire.chat.kit.third.utils.-$$Lambda$ImageUtils$2$1$8qc-DggK4Nv-DbCKFtDGCr7EHsE.run(Unknown Source:12)
        at java.lang.Thread.run(Thread.java:929)
2021-06-09 16:08:40.867 1087-1341/? E/Parcel: Reading a NULL string not supported here.
2021-06-09 16:08:40.897 22890-23355/com.superchain.lbanknew E/AndroidRuntime: FATAL EXCEPTION: Thread-37
    Process: com.superchain.lbanknew, PID: 22890
    java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
        at cn.wildfire.chat.kit.third.utils.ImageUtils$2$1.lambda$onSuccess$0$ImageUtils$2$1(ImageUtils.java:339)
        at cn.wildfire.chat.kit.third.utils.-$$Lambda$ImageUtils$2$1$8qc-DggK4Nv-DbCKFtDGCr7EHsE.run(Unknown Source:12)
        at java.lang.Thread.run(Thread.java:929)
```

**Comment by scsfwgy** [comment]
我不太确认这个问题，会不会因为我们的图片服务器还没打开？现在图片上传会报错的。
ImageUtils line:339
