### ISSUE TITLE
野火登录后接收消息 avengineKit 中 onReceiveCallMessage接收消息报空指针 

### ISSUE THREAD

**Issue by AsFreeBird** [wildfirechat/android-chat#563]
private void onReceiveMessage(final List<Message> messages, final boolean hasMore) {
        mainHandler.post(() -> {
            Iterator<OnReceiveMessageListener> iterator = onReceiveMessageListeners.iterator();
            OnReceiveMessageListener listener;
            while (iterator.hasNext()) {
                listener = iterator.next();
                listener.onReceiveMessage(messages, hasMore);  //报错 
            }
java.lang.NullPointerException: Attempt to read from field 'cn.wildfirechat.message.MessageContent cn.wildfirechat.message.Message.content' on a null object reference
        at cn.wildfirechat.avenginekit.AVEngineKit.onReceiveCallMessage(Unknown Source:0)
        at cn.wildfirechat.avenginekit.AVEngineKit.onReceiveMessage(Unknown Source:16)
        at cn.wildfirechat.remote.ChatManager.lambda$onReceiveMessage$1$ChatManager(ChatManager.java:397)
        at cn.wildfirechat.remote.-$$Lambda$ChatManager$rjJzsBA79a4yCN9aP7_PTSstc8Y.run(Unknown Source:6)

**Comment by imndx** [comment]
这个问题，最新代码应当已经修复了，请先更新到最新代码测试。
