### ISSUE TITLE
保存草稿出现 NullPointerException 异常

### ISSUE THREAD

**Issue by chenlin4653** [wildfirechat/android-chat#601]
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String cn.wildfirechat.model.ConversationInfo.draft' on a null object reference
        at android.os.Parcel.createException(Parcel.java:1959)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at cn.wildfirechat.client.IRemoteClient$Stub$Proxy.setConversationDraft(IRemoteClient.java:4071)
        at cn.wildfirechat.remote.ChatManager.setConversationDraft(ChatManager.java:3770)
        at com.msic.synergyoffice.message.viewmodel.other.MessageViewModel.saveDraft(MessageViewModel.java:406)

異常出現场景，当前用户停留在会话（聊天）页面，另一台手机登录当前用户账户就会回调保存草稿函数，抛出空指针异常，请跟进一下   mClient.setConversationDraft(conversation.type.ordinal(), conversation.target, conversation.line, draft);  
谢谢

**Comment by heavyrain2012** [comment]
是不是版本比较旧，用我们最新demo对比测试看看

**Comment by imndx** [comment]
可能这个提交已经修复 a8616b4bf4536b5913912293ca1098a854267b63
