### ISSUE TITLE
为什么点击语音通话和视频通话，那个界面没调用起来啊？

### ISSUE THREAD

**Issue by niushicha1** [wildfirechat/android-chat#735]
## 提issue小提示
为了尽快定位问题，需要提供足够的信息，请按照我们的要求格式来提问。***如果您不按照格式提问，我们将无法回复您的问题***

#### 操作说明
详细说明操作那个界面，每一步骤都要说得详细，如果是SDK或者api使用问题，需要详细说明调用的那个函数，参数都是什么。

#### 表现现象
描述一下什么现象，比如说函数返回error，errorcode是多少，或者界面上是什么状态，比如发送消息显示发送失败的红点。不要笼统的说功能有问题，不起作用。

#### 预期结果
你认为正确的表现应该是什么样的。

#### 补充条件
是否是必现的，还是偶现的？是否只有在特殊的网络/设备/平台上出现，还是所有的都出现。还有您用的版本是什么时候的，是不是最新版

#### demo对比结果
请用demo对比测试，demo上是什么状态。

**Comment by imndx** [comment]
真机，还是模拟器测试的？

有没有什么日志之类的？

**Comment by niushicha1** [comment]
> 真机，还是模拟器测试的？
> 
> 有没有什么日志之类的？

真机，没有报错的日志啊

**Comment by imndx** [comment]
```adb logcat > log.log```

然后复现问题，之后把 ```log.log```文件附上

**Comment by niushicha1** [comment]
> `adb logcat > log.log`
> 
> 然后复现问题，之后把 `log.log`文件附上

.wildfirechat.remote.ChatManager: init wildfirechat.net
2022-12-27 13:54:46.059 15804-15804/com.chainmaster.yuumi D/cn.wildfirechat.remote.ChatManager: *************** SDK检查 *****************
2022-12-27 13:54:46.069 15804-15804/com.chainmaster.yuumi D/cn.wildfirechat.remote.ChatManager: 音视频SDK是多人版
2022-12-27 13:54:46.071 15804-15804/com.chainmaster.yuumi W/System.err: java.lang.ClassNotFoundException: cn.wildfirechat.moment.MomentClient
2022-12-27 13:54:46.072 15804-15804/com.chainmaster.yuumi W/System.err:     at java.lang.Class.classForName(Native Method)
2022-12-27 13:54:46.072 15804-15804/com.chainmaster.yuumi W/System.err:     at java.lang.Class.forName(Class.java:453)
2022-12-27 13:54:46.073 15804-15804/com.chainmaster.yuumi W/System.err:     at java.lang.Class.forName(Class.java:378)
2022-12-27 13:54:46.073 15804-15804/com.chainmaster.yuumi W/System.err:     at cn.wildfirechat.remote.ChatManager.checkSDKHost(ChatManager.java:8539)
2022-12-27 13:54:46.073 15804-15804/com.chainmaster.yuumi W/System.err:     at cn.wildfirechat.remote.ChatManager.init(ChatManager.java:389)
2022-12-27 13:54:46.073 15804-15804/com.chainmaster.yuumi W/System.err:     at cn.wildfire.chat.kit.WfcUIKit.initWFClient(WfcUIKit.java:130)
2022-12-27 13:54:46.074 15804-15804/com.chainmaster.yuumi W/System.err:     at cn.wildfire.chat.kit.WfcUIKit.init(WfcUIKit.java:87)
2022-12-27 13:54:46.074 15804-15804/com.chainmaster.yuumi W/System.err:     at com.chainmaster.gamefi.MyApplication.onCreate(MyApplication.java:88)
2022-12-27 13:54:46.074 15804-15804/com.chainmaster.yuumi W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
2022-12-27 13:54:46.074 15804-15804/com.chainmaster.yuumi W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5966)
2022-12-27 13:54:46.075 15804-15804/com.chainmaster.yuumi W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:206)

**Comment by imndx** [comment]
> 

这里面没有包含相关日志，请确认下demo是否正常，如果demo正常的，可能是集成问题。
